pipeline:
    name: p1
    identifier: p1
    projectIdentifier: nvh_git_sync_2
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: a1
              identifier: a1
              description: "a1"
              type: Approval
              spec:
                  execution:
                      steps:
                          - step:
                                type: Http
                                name: search
                                identifier: search
                                spec:
                                    url: https://www.google.com
                                    method: GET
                                    headers: []
                                    outputVariables: []
                                timeout: 10s
                  serviceDependencies: []
              tags: {}
