pipeline:
    stages:
        - stage:
              type: Approval
              spec:
                  execution:
                      steps:
                          - step:
                                type: Http
                                timeout: 10s
                                spec:
                                    url: https://www.google.com
                                    method: GET
                                name: search
                                identifier: search
              name: a1
              identifier: a1
    projectIdentifier: nvh_git_sync_2
    orgIdentifier: default
    name: p1
    identifier: p1
